baseurl = "https://vikas-kumar.herokuapp.com/"
languageCode = "en-us"
title = "Vikas Kumar"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Vikas Kumar"
	description = "Software Engineer who loves to cook code."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Vikas Kumar"

		[params.navigation.links]
			about     = "About"
			services  = "Summary"
			portfolio = "Resume"
			contact   = "Contact Me!"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Software Engineer"
		subtitle   = "Hey! Are you looking for a software engineer who love to cook code for you then you are on the right place."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "About Me!"
		description = "I am Vikas Kumar from Bihar.I did Master of Computer Application from Jawaharlal Nehru University, New Delhi and Bachelor of Computer Application from, IGNOU."
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Me!"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Software Engineer"
            description = "@Byond.Travel"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Master of Computer Application"
			description = "Jawaharlal Nehru University, New Delhi"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Skills"
            description = "Python, PHP and Go"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Experience"
            description = "1.5 Years"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Please find my resume."

		[params.aside.button]
			text = "Resume"
			link = "https://www.dropbox.com/s/k1o1o5ii5pu4vln/Resume.docx.pdf?dl=0"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project? That's great! Give me a call or send me an email and i will get back to you as soon as possible!"
		phone = "+91 9620489445"
		email = "vikasmca2k11@gmail.com"
