baseurl = "https://codeifucansolve.herokuapp.com/"
title = "Code If You Can Solve!"
theme = "ghostwriter"
languageCode = "en-us"
copyright = ""
disqusShortname = "codeifyoucansolve"
googleAnalytics = "XXX"

[Author]
    name = "Code If You Can Solve!"
    profile = "https://plus.google.com/u/0/b/108302369847117270036/108302369847117270036"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Code If You Can Solve!"
    description = "CIYCS - Code If You Can Solve!"
    facebook = "https://www.facebook.com/codeifucansolve"
    twitter = "https://twitter.com/codeifucansolve"
[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4